### ISSUE TITLE
SIGABRT: abort issue

### ISSUE THREAD

**Issue by l6128589** [bytelang/kplayer-go#58]
```
kplayer for golang v0.5.7 Copyright(c) 2019-2022 the ByteLang Studio (https://kplayer.bytelang.cn)
  libkplayer version: v1.5.2 plugin version: 1.5.1 license version: v1 
  toolchains GNU(10.3.1) C++ Standard 17 on Linux-x86_64-5.18.14-arch1-1
  build with build-chains cmake(3.21.3) type with Release
  Hope you have a good experience.
--------------------------------------------------------------------------------
panic: getrandom failed
This message is indicative of a BUG.
Report this at https://github.com/nanomsg/nng/issues
SIGABRT: abort
PC=0x3239692 m=4 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x3239692
stack: frame={sp:0x7fe82caecf08, fp:0x0} stack=[0x7fe82cacd8b0,0x7fe82caed4b0)
0x00007fe82caece08:  0x000000000323db70  0x00007fe82caece40 
0x00007fe82caece18:  0x00007fe82caed097  0x000000000000004c 
0x00007fe82caece28:  0x0000000000000000  0x0000000000000000 
0x00007fe82caece38:  0x0000000000000000  0x0000000000000000 
0x00007fe82caece48:  0x0000000000000000  0x0000000000000000 
0x00007fe82caece58:  0x0000000000000000  0x0000000000000000 
0x00007fe82caece68:  0x0000000000000000  0x000000000323da44 
0x00007fe82caece78:  0x0000000000000000  0x00007fe82caece16 
0x00007fe82caece88:  0x0000000000000000  0x0000000000000000 
0x00007fe82caece98:  0x0000000000000000  0x0000000000000000 
0x00007fe82caecea8:  0x0000000000000000  0xffffffffffffffff 
0x00007fe82caeceb8:  0x00000000ffffffff  0x00007fe82caece18 
0x00007fe82caecec8:  0x0000000000000000  0x0000000000000000 
0x00007fe82caeced8:  0x0000000000000000  0x0000000000000000 
0x00007fe82caecee8:  0x0000000000000000  0x0000000000000000 
0x00007fe82caecef8:  0x0000000000000000  0x00007fe82caed080 
0x00007fe82caecf08: <0x00000000032396eb  0x0000000000000000 
0x00007fe82caecf18:  0x0000000000000000  0x0000000003550230 
0x00007fe82caecf28:  0x0000000000000034  0x00007fe82caed000 
0x00007fe82caecf38:  0x0000000000000001  0x00000000045a7f20 
0x00007fe82caecf48:  0x0000000000000034  0x0000000000000001 
0x00007fe82caecf58:  0x000000000323a2a2  0x0000000004f6eee8 
0x00007fe82caecf68:  0x0000000000000000  0x00007fe82caecfcf 
0x00007fe82caecf78:  0x0000000000000001  0x00007fe82caecff0 
0x00007fe82caecf88:  0x00000000045a7f20  0x000000000000000a 
0x00007fe82caecf98:  0x000000000464a800  0x00007fe82caecff0 
0x00007fe82caecfa8:  0x000000000322bebe  0x00007fe82caed390 
0x00007fe82caecfb8:  0x00000000032480a6  0x0000000000000000 
0x00007fe82caecfc8:  0x0a0000000464a800  0x00000000045a7f20 
0x00007fe82caecfd8:  0x000000000323a983  0x000000000464a800 
0x00007fe82caecfe8:  0x0000000000419e5f  0x00007fe82caed1b0 
0x00007fe82caecff8:  0x0000000000e9721e  0x0000000000000000 
runtime: unknown pc 0x3239692
stack: frame={sp:0x7fe82caecf08, fp:0x0} stack=[0x7fe82cacd8b0,0x7fe82caed4b0)
0x00007fe82caece08:  0x000000000323db70  0x00007fe82caece40 
0x00007fe82caece18:  0x00007fe82caed097  0x000000000000004c 
0x00007fe82caece28:  0x0000000000000000  0x0000000000000000 
0x00007fe82caece38:  0x0000000000000000  0x0000000000000000 
0x00007fe82caece48:  0x0000000000000000  0x0000000000000000 
0x00007fe82caece58:  0x0000000000000000  0x0000000000000000 
0x00007fe82caece68:  0x0000000000000000  0x000000000323da44 
0x00007fe82caece78:  0x0000000000000000  0x00007fe82caece16 
0x00007fe82caece88:  0x0000000000000000  0x0000000000000000 
0x00007fe82caece98:  0x0000000000000000  0x0000000000000000 
0x00007fe82caecea8:  0x0000000000000000  0xffffffffffffffff 
0x00007fe82caeceb8:  0x00000000ffffffff  0x00007fe82caece18 
0x00007fe82caecec8:  0x0000000000000000  0x0000000000000000 
0x00007fe82caeced8:  0x0000000000000000  0x0000000000000000 
0x00007fe82caecee8:  0x0000000000000000  0x0000000000000000 
0x00007fe82caecef8:  0x0000000000000000  0x00007fe82caed080 
0x00007fe82caecf08: <0x00000000032396eb  0x0000000000000000 
0x00007fe82caecf18:  0x0000000000000000  0x0000000003550230 
0x00007fe82caecf28:  0x0000000000000034  0x00007fe82caed000 
0x00007fe82caecf38:  0x0000000000000001  0x00000000045a7f20 
0x00007fe82caecf48:  0x0000000000000034  0x0000000000000001 
0x00007fe82caecf58:  0x000000000323a2a2  0x0000000004f6eee8 
0x00007fe82caecf68:  0x0000000000000000  0x00007fe82caecfcf 
0x00007fe82caecf78:  0x0000000000000001  0x00007fe82caecff0 
0x00007fe82caecf88:  0x00000000045a7f20  0x000000000000000a 
0x00007fe82caecf98:  0x000000000464a800  0x00007fe82caecff0 
0x00007fe82caecfa8:  0x000000000322bebe  0x00007fe82caed390 
0x00007fe82caecfb8:  0x00000000032480a6  0x0000000000000000 
0x00007fe82caecfc8:  0x0a0000000464a800  0x00000000045a7f20 
0x00007fe82caecfd8:  0x000000000323a983  0x000000000464a800 
0x00007fe82caecfe8:  0x0000000000419e5f  0x00007fe82caed1b0 
0x00007fe82caecff8:  0x0000000000e9721e  0x0000000000000000 

goroutine 1 [syscall]:
runtime.cgocall(0xc6095a, 0xc00029f920)
	/usr/lib/go/src/runtime/cgocall.go:156 +0x5c fp=0xc00029f8f8 sp=0xc00029f8c0 pc=0x5a1ffc
github.com/bytelang/kplayer/core._Cfunc_Initialization(0x7fe853851d00, 0x356, 0x1e0, 0x0, 0x0, 0x19, 0xac44, 0x3, 0x2, 0x0)
	/tmp/go-build3453862433/b102/_cgo_gotypes.go:292 +0x4c fp=0xc00029f920 sp=0xc00029f8f8 pc=0xae642c
github.com/bytelang/kplayer/core.(*libKplayer).Initialization(0x453da80)
	core/kplayer.go:220 +0x125 fp=0xc00029f968 sp=0xc00029f920 pc=0xae7d45
github.com/bytelang/kplayer/module/play/provider.startCommand.func2(0xc00042c000, {0x33bb409, 0x0, 0x0})
	module/play/provider/command.go:433 +0xef2 fp=0xc00029fd28 sp=0xc00029f968 pc=0xc0ab52
github.com/spf13/cobra.(*Command).execute(0xc00042c000, {0x4f70718, 0x0, 0x0})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:856 +0x60e fp=0xc00029fde8 sp=0xc00029fd28 pc=0x9dd74e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003e7180)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc fp=0xc00029fea0 sp=0xc00029fde8 pc=0x9dde3c
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:895
github.com/bytelang/kplayer/types.SetCommandContextAndExecute(...)
	types/context.go:49
main.Execute(0xc0003e7180, {0x33b9d98, 0x2}, {0x33c2ab3, 0x6})
	main.go:85 +0x345 fp=0xc00029ff48 sp=0xc00029fea0 pc=0xc5ea65
main.main()
	main.go:47 +0x36 fp=0xc00029ff80 sp=0xc00029ff48 pc=0xc5e6d6
runtime.main()
	/usr/lib/go/src/runtime/proc.go:255 +0x227 fp=0xc00029ffe0 sp=0xc00029ff80 pc=0x5d4b07
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00029ffe8 sp=0xc00029ffe0 pc=0x602761

goroutine 9 [runnable]:
github.com/bytelang/kplayer/module/play/provider.startCommand.func2.2()
	module/play/provider/command.go:391
created by github.com/bytelang/kplayer/module/play/provider.startCommand.func2
	module/play/provider/command.go:391 +0xda5

goroutine 10 [runnable]:
github.com/bytelang/kplayer/module/play/provider.startCommand.func2.3()
	module/play/provider/command.go:415
created by github.com/bytelang/kplayer/module/play/provider.startCommand.func2
	module/play/provider/command.go:415 +0xe9a

rax    0x0
rbx    0x0
rcx    0xffffffffffffffff
rdx    0x0
rdi    0x2
rsi    0x7fe82caecf10
rbp    0x7fe82caecf10
rsp    0x7fe82caecf08
r8     0xa
r9     0x3a52f6f
r10    0x8
r11    0x246
r12    0x7fe82caed080
r13    0x7fe82caed020
r14    0x1
r15    0x7fe82caed390
rip    0x3239692
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

```

**Comment by l6128589** [comment]
Linux version 3.13.0-32-generic (buildd@kissel) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014

**Comment by vaptu** [comment]
尝试使用个更高内核的Linux发行版本来运行，该问题已处理 下版本迭代可以解决这个问题

**Comment by vaptu** [comment]
v0.5.8版本已解决上述问题，重新下载使用
