### ISSUE TITLE
0.58版本运行报错

### ISSUE THREAD

**Issue by Asuna521** [bytelang/kplayer-go#75]
kplayer for golang v0.5.8 Copyright(c)2019-2023 the ByteLang Studio (https://143.226.152.249 root@localhost:
libkplayer version:v1.5.4-1-ge0cab16 plugin version:1.5.1 license version:v1
toolchains GNU(10.3.1)C++Standard 17 on Linux-x86 64-6.0.2-arch1-1
build with build-chains cmake(3.21.3)type with Release
Hope you have a good experience.
panic:interface conversion:interface {is map[string]interface {}not []interface
goroutine 1 [running]:
main.InitGlobalContextConfig(0xc0003ddb80)
ain.g0:133+0x1586
main.Execute.func1(0xc0003ddb80,{0x33f5ed6,0x2,0x2})
main.go:76 +0xb0
github.com/spf13/cobra.(*Command).execute(0xc0003ddb80,{0xc00044e0c0,0x2,0x2})
/root/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:835 +0x52f
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003dcf00)
/root/go/pkg/mod/github.com/spf13/cobradv1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
/root/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
/root/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:895
github.com/bytelang/kplayer/types.SetCommandContextAndExecute(...)
types/context.go:49
main.Execute(0xc0003dcf00,{0x33f4859,0x2},{0x33fd5a7,0x6})
main.g0:85+0x345
main.main (
main.g0:47+0x36

**Comment by vaptu** [comment]
请贴上配置文件，这个错误提示配置文件中的配置变量类型不正确
