### ISSUE TITLE
音频+视频（插件）报错

### ISSUE THREAD

**Issue by ciihom** [bytelang/kplayer-go#80]
资源配置音频文件夹和一个media插件，运行报错
kplayer for golang v0.5.8 Copyright(c) 2019-2023 the ByteLang Studio (https://kplayer.bytelang.cn)
  libkplayer version: v1.5.4-1-ge0cab16 plugin version: 1.5.1 license version: v1 
  toolchains GNU(10.3.1) C++ Standard 17 on Linux-x86_64-6.0.2-arch1-1
  build with build-chains cmake(3.21.3) type with Release
  Hope you have a good experience.
----------------------------------------------------------------------------------------------------------
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0xc417bf]

goroutine 1 [running]:
github.com/bytelang/kplayer/module/resource/provider.CalcMixResourceGroupPrimaryPath({0xc0000b4528, 0x1, 0x10000032bf160})
	module/resource/provider/keys.go:121 +0x19f
github.com/bytelang/kplayer/module/resource/provider.(*Provider).InitModule(0xc0003cde40, 0x5f2e0a, 0xc0003be780)
	module/resource/provider/provider.go:125 +0x696
github.com/bytelang/kplayer/module/resource.AppModule.InitConfig({0x5}, 0xc0004c70a8, {0xc0000f22c0, 0xb0, 0xb0})
	module/resource/module.go:38 +0xb8
main.InitGlobalContextConfig(0xc000417900)
	main.go:228 +0xd6d
main.Execute.func1(0xc000417900, {0x33f5ed6, 0x0, 0x0})
	main.go:76 +0xb0
github.com/spf13/cobra.(*Command).execute(0xc000417900, {0x4fec338, 0x0, 0x0})
	/root/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:835 +0x52f
github.com/spf13/cobra.(*Command).ExecuteC(0xc000416780)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:895
github.com/bytelang/kplayer/types.SetCommandContextAndExecute(...)
	types/context.go:49
main.Execute(0xc000416780, {0x33f4859, 0x2}, {0x33fd5a7, 0x6})
	main.go:85 +0x345
main.main()
	main.go:47 +0x36

**Comment by vaptu** [comment]
请提供log/core.log下的日志文件。文件夹不会遍历读取子目录下的视频资源
